<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ProductController extends Controller
{
    public function index(Request $request){
        $store_type_id = $request->store_type_id;
        $genre_id = $request->genre_id;
        //$products = Product:all();
            $products = [
                [
                    'id' => 1,
                    'name' => '梅おにぎり',
                    'store_type_id' => 1,
                    'genre_id' => 1,
                    'img_filename' => '',
                    'calorie' => 100,
                    'price' => 150,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 2,
                    'name' => '鮭おにぎり',  
                    'store_type_id' => 1,
                    'genre_id' => 1,
                    'img_filename' => '',
                    'calorie' => 150,
                    'price' => 200,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 3,
                    'name' => '昆布おにぎり',  
                    'store_type_id' => 1,
                    'genre_id' => 1,
                    'img_filename' => '',
                    'calorie' => 200,
                    'price' => 250,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 4,
                    'name' => '納豆巻き',  
                    'store_type_id' => 1,
                    'genre_id' => 1,
                    'img_filename' => '',
                    'calorie' => 300,
                    'price' => 100,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 5,
                    'name' => 'セブンイレブンおにぎり',  
                    'store_type_id' => 1,
                    'genre_id' => 1,
                    'img_filename' => '',
                    'calorie' => 300,
                    'price' => 250,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 6,
                    'name' => 'ガリガリくん',  
                    'store_type_id' => 1,
                    'genre_id' => 2,
                    'img_filename' => '',
                    'calorie' => 50,
                    'price' => 70,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 7,
                    'name' => 'ピノ',  
                    'store_type_id' => 1,
                    'genre_id' => 2,
                    'img_filename' => '',
                    'calorie' => 300,
                    'price' => 150,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 8,
                    'name' => 'クーリッシュ',  
                    'store_type_id' => 1,
                    'genre_id' => 2,
                    'img_filename' => '',
                    'calorie' => 100,
                    'price' => 100,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 9,
                    'name' => 'ハーゲンダッツ',  
                    'store_type_id' => 1,
                    'genre_id' => 2,
                    'img_filename' => '',
                    'calorie' => 300,
                    'price' => 250,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 10,
                    'name' => 'セブンイレブンアイス',  
                    'store_type_id' => 1,
                    'genre_id' => 2,
                    'img_filename' => '',
                    'calorie' => 200,
                    'price' => 200,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 11,
                    'name' => '豚カルビ弁当',  
                    'store_type_id' => 1,
                    'genre_id' => 3,
                    'img_filename' => '',
                    'calorie' => 500,
                    'price' => 500,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 12,
                    'name' => '牛丼',  
                    'store_type_id' => 1,
                    'genre_id' => 3,
                    'img_filename' => '',
                    'calorie' => 600,
                    'price' => 400,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 13,
                    'name' => '明太子パスタ',  
                    'store_type_id' => 1,
                    'genre_id' => 3,
                    'img_filename' => '',
                    'calorie' => 600,
                    'price' => 550,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 14,
                    'name' => 'カレー',  
                    'store_type_id' => 1,
                    'genre_id' => 3,
                    'img_filename' => '',
                    'calorie' => 700,
                    'price' => 500,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 15,
                    'name' => 'セブンイレブン弁当',  
                    'store_type_id' => 1,
                    'genre_id' => 3,
                    'img_filename' => '',
                    'calorie' => 1000,
                    'price' => 1000,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 16,
                    'name' => 'レッドブル',  
                    'store_type_id' => 1,
                    'genre_id' => 4,
                    'img_filename' => '',
                    'calorie' => 300,
                    'price' => 200,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 17,
                    'name' => '麦茶',  
                    'store_type_id' => 1,
                    'genre_id' => 4,
                    'img_filename' => '',
                    'calorie' => 100,
                    'price' => 150,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 18,
                    'name' => '天然水',  
                    'store_type_id' => 1,
                    'genre_id' => 4,
                    'img_filename' => '',
                    'calorie' => 0,
                    'price' => 100,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 19,
                    'name' => 'ファンタオレンジ',  
                    'store_type_id' => 1,
                    'genre_id' => 4,
                    'img_filename' => '',
                    'calorie' => 150,
                    'price' => 150,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 20,
                    'name' => 'セブンイレブンジュース',  
                    'store_type_id' => 1,
                    'genre_id' => 4,
                    'img_filename' => '',
                    'calorie' => 300,
                    'price' => 300,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 21,
                    'name' => 'クレープ',  
                    'store_type_id' => 1,
                    'genre_id' => 5,
                    'img_filename' => '',
                    'calorie' => 300,
                    'price' => 200,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 22,
                    'name' => '大福',  
                    'store_type_id' => 1,
                    'genre_id' => 5,
                    'img_filename' => '',
                    'calorie' => 200,
                    'price' => 250,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 23,
                    'name' => 'クッキー',  
                    'store_type_id' => 1,
                    'genre_id' => 5,
                    'img_filename' => '',
                    'calorie' => 200,
                    'price' => 150,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 24,
                    'name' => 'チョコレートケーキ',  
                    'store_type_id' => 1,
                    'genre_id' => 5,
                    'img_filename' => '',
                    'calorie' => 300,
                    'price' => 250,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 25,
                    'name' => 'セブンイレブンスイーツ',  
                    'store_type_id' => 1,
                    'genre_id' => 5,
                    'img_filename' => '',
                    'calorie' => 500,
                    'price' => 500,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 26,
                    'name' => 'ネギトロおにぎり',  
                    'store_type_id' => 2,
                    'genre_id' => 1,
                    'img_filename' => '',
                    'calorie' => 150,
                    'price' => 130,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 27,
                    'name' => '筋子おにぎり',  
                    'store_type_id' => 2,
                    'genre_id' => 1,
                    'img_filename' => '',
                    'calorie' => 180,
                    'price' => 150,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 28,
                    'name' => 'ファミリーマートおにぎり',  
                    'store_type_id' => 2,
                    'genre_id' => 1,
                    'img_filename' => '',
                    'calorie' => 500,
                    'price' => 500,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 29,
                    'name' => 'チョコモナカジャンボ',  
                    'store_type_id' => 2,
                    'genre_id' => 2,
                    'img_filename' => '',
                    'calorie' => 200,
                    'price' => 200,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 30,
                    'name' => 'パルム',  
                    'store_type_id' => 2,
                    'genre_id' => 2,
                    'img_filename' => '',
                    'calorie' => 250,
                    'price' => 180,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 31,
                    'name' => 'ファミリーマートアイス',  
                    'store_type_id' => 2,
                    'genre_id' => 2,
                    'img_filename' => '',
                    'calorie' => 500,
                    'price' => 500,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 32,
                    'name' => 'のり弁当',  
                    'store_type_id' => 2,
                    'genre_id' => 3,
                    'img_filename' => '',
                    'calorie' => 400,
                    'price' => 300,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 33,
                    'name' => 'からあげ弁当',  
                    'store_type_id' => 2,
                    'genre_id' => 3,
                    'img_filename' => '',
                    'calorie' => 700,
                    'price' => 600,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 34,
                    'name' => 'ファミリーマート弁当',  
                    'store_type_id' => 2,
                    'genre_id' => 3,
                    'img_filename' => '',
                    'calorie' => 1000,
                    'price' => 1000,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 35,
                    'name' => 'アクエリアス',  
                    'store_type_id' => 2,
                    'genre_id' => 4,
                    'img_filename' => '',
                    'calorie' => 150,
                    'price' => 150,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 36,
                    'name' => 'カルピス',  
                    'store_type_id' => 2,
                    'genre_id' => 4,
                    'img_filename' => '',
                    'calorie' => 200,
                    'price' => 120,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 37,
                    'name' => 'ファミリーマートジュース',  
                    'store_type_id' => 2,
                    'genre_id' => 4,
                    'img_filename' => '',
                    'calorie' => 300,
                    'price' => 300,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 38,
                    'name' => 'たい焼き',  
                    'store_type_id' => 2,
                    'genre_id' => 5,
                    'img_filename' => '',
                    'calorie' => 300,
                    'price' => 200,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 39,
                    'name' => 'お団子',  
                    'store_type_id' => 2,
                    'genre_id' => 5,
                    'img_filename' => '',
                    'calorie' => 300,
                    'price' => 250,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 40,
                    'name' => 'ファミリーマートスイーツ',  
                    'store_type_id' => 2,
                    'genre_id' => 5,
                    'img_filename' => '',
                    'calorie' => 500,
                    'price' => 500,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 41,
                    'name' => 'ローソンおにぎり',  
                    'store_type_id' => 3,
                    'genre_id' => 1,
                    'img_filename' => '',
                    'calorie' => 300,
                    'price' => 300,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 42,
                    'name' => 'ローソンアイス',  
                    'store_type_id' => 3,
                    'genre_id' => 2,
                    'img_filename' => '',
                    'calorie' => 300,
                    'price' => 300,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 43,
                    'name' => 'ローソンお弁当',  
                    'store_type_id' => 3,
                    'genre_id' => 3,
                    'img_filename' => '',
                    'calorie' => 1000,
                    'price' => 1000,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 44,
                    'name' => 'ローソンジュース',  
                    'store_type_id' => 3,
                    'genre_id' => 4,
                    'img_filename' => '',
                    'calorie' => 500,
                    'price' => 500,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 45,
                    'name' => 'ローソンスイーツ',  
                    'store_type_id' => 3,
                    'genre_id' => 5,
                    'img_filename' => '',
                    'calorie' => 300,
                    'price' => 300,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 46,
                    'name' => 'デイリーヤマザキおにぎり',  
                    'store_type_id' => 4,
                    'genre_id' => 1,
                    'img_filename' => '',
                    'calorie' => 300,
                    'price' => 200,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 47,
                    'name' => 'デイリーヤマザキアイス',  
                    'store_type_id' => 4,
                    'genre_id' => 2,
                    'img_filename' => '',
                    'calorie' => 300,
                    'price' => 300,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 48,
                    'name' => 'デイリーヤマザキお弁当',  
                    'store_type_id' => 4,
                    'genre_id' => 3,
                    'img_filename' => '',
                    'calorie' => 1000,
                    'price' => 250,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 49,
                    'name' => 'デイリーヤマザキジュース',  
                    'store_type_id' => 4,
                    'genre_id' => 4,
                    'img_filename' => '',
                    'calorie' => 300,
                    'price' => 300,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 50,
                    'name' => 'デイリーヤマザキスイーツ',  
                    'store_type_id' => 4,
                    'genre_id' => 5,
                    'img_filename' => '',
                    'calorie' => 300,
                    'price' => 300,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 51,
                    'name' => 'ミニストップおにぎり',  
                    'store_type_id' => 5,
                    'genre_id' => 1,
                    'img_filename' => '',
                    'calorie' => 300,
                    'price' => 250,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],                [
                    'id' => 52,
                    'name' => 'ミニストップアイス',  
                    'store_type_id' => 5,
                    'genre_id' => 2,
                    'img_filename' => '',
                    'calorie' => 300,
                    'price' => 200,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 53,
                    'name' => 'ミニストップお弁当',  
                    'store_type_id' => 5,
                    'genre_id' => 3,
                    'img_filename' => '',
                    'calorie' => 1000,
                    'price' => 500,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 54,
                    'name' => 'ミニストップジュース',  
                    'store_type_id' => 5,
                    'genre_id' => 4,
                    'img_filename' => '',
                    'calorie' => 300,
                    'price' => 250,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],
                [
                    'id' => 55,
                    'name' => 'デイリーヤマザキスイーツ',  
                    'store_type_id' => 5,
                    'genre_id' => 5,
                    'img_filename' => '',
                    'calorie' => 400,
                    'price' => 300,
                    'admin_id' => '',
                    'created_at' => '',
                    'updated_at' => '',
                    'deleted_at' => '',
                ],


            ];
            return view('product.index', compact('store_type_id', 'genre_id', 'products'));
    }
    
}